language: cpp

dist: xenial
sudo: required

matrix:
  include:
    - os: linux
    # OSX is failing with illegal instruction, disabling for now
    #- os: osx

before_install:
  # Install clangformat (v5.0)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo scripts/install-clangformat.sh;
    fi

install:
  - mkdir build
  - pushd build
  - cmake ..
  - make check-format
  - make -j2
  - popd

script:
  - mkdir test_arrays
  - ./build/NYSE_Ingestor/NYSE_Ingestor --array "./test_arrays/master" --type Master --create
  - ./build/NYSE_Ingestor/NYSE_Ingestor --array "./test_arrays/quote" --type Quote --create
  - ./build/NYSE_Ingestor/NYSE_Ingestor --array "./test_arrays/trade" --type Trade --create
  - ./build/NYSE_Ingestor/NYSE_Ingestor --array "./test_arrays/master" --type Master --files "./sample_data/small_EQY_US_ALL_REF_MASTER_20180306"
  - ./build/NYSE_Ingestor/NYSE_Ingestor --array "./test_arrays/quote" --type Quote --files "./sample_data/small_SPLITS_US_ALL_BBO_Z_20180730" --master_file "./sample_data/small_EQY_US_ALL_REF_MASTER_20180306"
  - ./build/NYSE_Ingestor/NYSE_Ingestor --array "./test_arrays/trade" --type Trade --files "./sample_data/small_EQY_US_ALL_TRADE_20180730" --master_file "./sample_data/small_EQY_US_ALL_REF_MASTER_20180306"
